<?php

/**
 * Implements hook_page_attachments().
 */
function toastr_page_attachments(array &$attachments) {
  // Get all the Drupal status messages, so they do not appear anywhere else.
  $messages = \Drupal::messenger()->deleteAll();
  if (!empty($messages)) {
    // Get toastr configs.
    $config = \Drupal::config('toastr.settings');
    // Get default settings.
    $default_settings = \Drupal\toastr\Form\ToastrSettingsForm::defaultSettings();
    $keys = array_keys($default_settings);
    foreach ($keys as $key) {
      $settings[$key] = is_null($config->get($key)) ? $default_settings[$key] : $config->get($key);
    }
    $attachments['#attached']['drupalSettings']['toastr'] = [];
    $attachments['#attached']['drupalSettings']['toastr']['messages'] = $messages;
    $attachments['#attached']['drupalSettings']['toastr']['settings'] = $settings;
    // Unconditionally attach an asset to the page.
    $attachments['#attached']['library'][] = 'toastr/messages';
  }
}
